// UNIT_TYPE=Test
// useResourcesAnalysisParser tests — Phase 2 of Resources beef-up (r88).
// Tom Gilb 2026-06-04: *"I am keen to push resources far"*.

import { describe, it, expect } from 'vitest'
import {
  parseResourcesAnalysis,
  applyApprovedToSpec,
  promoteREntry,
  promoteSEntry,
  promoteCEntry,
  type ResourcesAnalysisOutput,
  type ApprovalSet,
} from '../useResourcesAnalysisParser'
import type { SpecBlock } from '../../types/spec'

// ── Fixtures ──────────────────────────────────────────────────────────────────

function emptySpec(): SpecBlock {
  return { functions: [], values: [], solutions: [], constraints: [], resources: [] }
}

const goodAnalysis: ResourcesAnalysisOutput = {
  schemaVersion: '1',
  partA: {
    'calendar-time': [
      {
        dimensionId: 'calendar-time',
        title:       'Delivery deadline tight against specialist availability',
        description: 'The 120-day Goal assumes Senior Naval Architect available Q1; competing project may extend window.',
        severity:    'warning',
        source:      'cited-from-gilb',
        gilbCite:    'CE (Competitive Engineering, 2005) — Resource specification chapter.',
        proposedREntry: {
          id:        'R.SpecialistAvailability.NavalArchitect',
          scale:     'qualified architect-weeks committed [Phase = pre-keel-laying]',
          tolerable: 'Tolerable [Phase = pre-keel-laying] = 8 architect-weeks',
          goal:      'Goal [Phase = pre-keel-laying] = 12 architect-weeks',
        },
        tradeoff: {
          axis:       'V.DeliveryTimeline',
          give:       'Drop Goal date from 120 → 140 days',
          save:       '4 architect-weeks of contention',
          approvedBy: 'Sponsor',
        },
      },
    ],
  },
  partB: {
    'resource-constraint-specs': {
      toolId: 'resource-constraint-specs',
      proposedREntries: [
        {
          id:        'R.CalendarBudget',
          scale:     'days from project start [Sponsor approval]',
          meter:     'Project Gantt closed-out at delivery sign-off',
          tolerable: 'Tolerable [Sponsor, Worst-Case] = 180 days',
          goal:      'Goal [Sponsor, Best-Case] = 120 days',
        },
      ],
    },
    'binary-constraints-for-resources': {
      toolId: 'binary-constraints-for-resources',
      proposedCEntries: [
        {
          id:          'C.NoOvertimeOverEightyHoursPerWeek',
          description: 'No engineer shall work more than 80 hours in any rolling 4-week window.',
          scope:       'All engineers on the Ironclad project across all phases.',
          rationale:   'Sustainability + quality compounding cost; protects R.WorkHours budget.',
        },
      ],
    },
    'resource-management-strategies': {
      toolId: 'resource-management-strategies',
      proposedSEntries: [
        {
          id:          'S.FixedPriceVendorContract',
          description: 'Convert SteamEngine procurement from time-and-materials to fixed-price.',
          impact:      'R.CapitalBudget ~caps volatility at ±5%',
          function:    'F.IronclladDesignAndConstruct',
        },
      ],
    },
    'scale-and-meter-improvement': {
      toolId: 'scale-and-meter-improvement',
      proposedFieldEdits: [
        {
          entryId:       'V.SpeedUnderSail',
          field:         'scale',
          currentValue:  'knots in sea trials',
          proposedValue: 'knots [Wind-Speed = 10-20 kt, Sea-State ≤ 3, Heading = Beam-Reach]',
          rationale:     'Adds Where/What qualifiers per CE Scale Qualifier chapter.',
          source:        'cited-from-gilb',
          gilbCite:      'CE 2005 — Scale + Meter chapter.',
        },
      ],
    },
  },
  notes: 'Generated by Claudian session 2026-06-04 23:55.',
}

// ── Parser tests ──────────────────────────────────────────────────────────────

describe('parseResourcesAnalysis — happy path', () => {
  it('round-trips a fully-formed analysis JSON', () => {
    const { ok, data, errors, warnings } = parseResourcesAnalysis(JSON.stringify(goodAnalysis))
    expect(ok).toBe(true)
    expect(errors).toEqual([])
    expect(warnings).toEqual([])
    expect(data?.schemaVersion).toBe('1')
    expect(data?.partA?.['calendar-time']).toHaveLength(1)
    expect(data?.partA?.['calendar-time']?.[0].title).toContain('Delivery deadline tight')
    expect(data?.partA?.['calendar-time']?.[0].proposedREntry?.id).toBe('R.SpecialistAvailability.NavalArchitect')
    expect(data?.partA?.['calendar-time']?.[0].tradeoff?.approvedBy).toBe('Sponsor')
    expect(data?.partB?.['resource-constraint-specs']?.proposedREntries).toHaveLength(1)
    expect(data?.partB?.['binary-constraints-for-resources']?.proposedCEntries).toHaveLength(1)
    expect(data?.partB?.['resource-management-strategies']?.proposedSEntries).toHaveLength(1)
    expect(data?.partB?.['scale-and-meter-improvement']?.proposedFieldEdits).toHaveLength(1)
  })

  it('passes through unknown extra fields without complaint (forward-compat)', () => {
    const withExtras = { ...goodAnalysis, futureField: 'whatever' }
    const { ok } = parseResourcesAnalysis(JSON.stringify(withExtras))
    expect(ok).toBe(true)
  })

  it('accepts empty partA / partB but emits warning', () => {
    const { ok, warnings } = parseResourcesAnalysis(JSON.stringify({}))
    expect(ok).toBe(true)
    expect(warnings.some((w) => w.includes('No `partA` or `partB`'))).toBe(true)
  })
})

describe('parseResourcesAnalysis — error paths', () => {
  it('rejects empty input', () => {
    const { ok, errors } = parseResourcesAnalysis('')
    expect(ok).toBe(false)
    expect(errors[0]).toContain('Input is empty')
  })

  it('rejects malformed JSON with the parse-error message', () => {
    const { ok, errors } = parseResourcesAnalysis('{not json')
    expect(ok).toBe(false)
    expect(errors[0]).toContain('Not valid JSON')
  })

  it('rejects non-object top-level', () => {
    expect(parseResourcesAnalysis('[]').ok).toBe(false)
    expect(parseResourcesAnalysis('"string"').ok).toBe(false)
    expect(parseResourcesAnalysis('42').ok).toBe(false)
  })

  it('rejects partA that is not an object', () => {
    const { ok, errors } = parseResourcesAnalysis(JSON.stringify({ partA: 'string' }))
    expect(ok).toBe(false)
    expect(errors.some((e) => e.includes('partA'))).toBe(true)
  })

  it('rejects a non-array dimension under partA', () => {
    const { ok, errors } = parseResourcesAnalysis(JSON.stringify({ partA: { 'calendar-time': 'oops' } }))
    expect(ok).toBe(false)
    expect(errors.some((e) => e.includes('partA.calendar-time'))).toBe(true)
  })

  it('requires title on every finding', () => {
    const { ok, errors } = parseResourcesAnalysis(JSON.stringify({
      partA: { 'calendar-time': [{ description: 'missing title' }] }
    }))
    expect(ok).toBe(false)
    expect(errors.some((e) => e.includes('title'))).toBe(true)
  })

  it('warns when severity is invalid but defaults to info', () => {
    const { ok, data, warnings } = parseResourcesAnalysis(JSON.stringify({
      partA: { 'calendar-time': [{ title: 'X', description: 'y', severity: 'meh' }] }
    }))
    expect(ok).toBe(true)
    expect(data?.partA?.['calendar-time']?.[0].severity).toBe('info')
    expect(warnings.some((w) => w.includes('severity'))).toBe(true)
  })

  it('warns when source=cited-from-gilb but gilbCite missing (provenance unverifiable)', () => {
    const { warnings } = parseResourcesAnalysis(JSON.stringify({
      partA: { 'calendar-time': [{ title: 'X', description: 'y', source: 'cited-from-gilb' }] }
    }))
    expect(warnings.some((w) => w.includes('cited-from-gilb but no gilbCite'))).toBe(true)
  })
})

// ── Promotion tests ───────────────────────────────────────────────────────────

describe('promote* — proposal → entry expansion', () => {
  it('promoteREntry fills type=Resource + sane defaults for omitted fields', () => {
    const e = promoteREntry({ id: 'R.A', scale: 's', tolerable: 't', goal: 'g' })
    expect(e.type).toBe('Resource')
    expect(e.level).toBe('Product')
    expect(e.meter).toBe('')
    expect(e.status).toBe('')
    expect(e.wish).toBeUndefined()
  })

  it('promoteSEntry fills type=Solution', () => {
    const e = promoteSEntry({ id: 'S.A', description: 'd', impact: 'i' })
    expect(e.type).toBe('Solution')
    expect(e.function).toBe('')
  })

  it('promoteCEntry fills type=Constraint', () => {
    const e = promoteCEntry({ id: 'C.A', description: 'd' })
    expect(e.type).toBe('Constraint')
    expect(e.scope).toBe('')
    expect(e.rationale).toBe('')
  })
})

// ── Apply-handler tests ───────────────────────────────────────────────────────

describe('applyApprovedToSpec — write-back behaviour', () => {
  const approvals: ApprovalSet = {
    rEntries:   [{ id: 'R.A', scale: 's', tolerable: 't', goal: 'g' }],
    sEntries:   [{ id: 'S.A', description: 'd', impact: 'i' }],
    cEntries:   [{ id: 'C.A', description: 'd' }],
    fieldEdits: [],
  }

  it('adds new R/S/C entries to an empty spec', () => {
    const next = applyApprovedToSpec(emptySpec(), approvals)
    expect(next.resources).toHaveLength(1)
    expect(next.solutions).toHaveLength(1)
    expect(next.constraints).toHaveLength(1)
    expect(next.resources?.[0].id).toBe('R.A')
  })

  it('is idempotent — applying twice yields the same result (upsert by id)', () => {
    const first  = applyApprovedToSpec(emptySpec(), approvals)
    const second = applyApprovedToSpec(first, approvals)
    expect(second.resources).toHaveLength(1)
    expect(second.solutions).toHaveLength(1)
    expect(second.constraints).toHaveLength(1)
  })

  it('does NOT mutate the input spec', () => {
    const spec = emptySpec()
    applyApprovedToSpec(spec, approvals)
    expect(spec.resources).toEqual([])
    expect(spec.solutions).toEqual([])
    expect(spec.constraints).toEqual([])
  })

  it('preserves existing entries with different ids', () => {
    const spec: SpecBlock = {
      ...emptySpec(),
      resources:   [{ id: 'R.Existing',   type: 'Resource',   level: 'Product', description: 'x', scale: '', meter: '', status: '', tolerable: '', goal: '' }],
      solutions:   [{ id: 'S.Existing',   type: 'Solution',   level: 'Product', description: 'x', impact: '', function: '' }],
      constraints: [{ id: 'C.Existing',   type: 'Constraint', level: 'Product', description: 'x', scope: '', rationale: '' }],
    }
    const next = applyApprovedToSpec(spec, approvals)
    expect(next.resources?.map((r) => r.id).sort()).toEqual(['R.A', 'R.Existing'])
    expect(next.solutions?.map((s) => s.id).sort()).toEqual(['S.A', 'S.Existing'])
    expect(next.constraints?.map((c) => c.id).sort()).toEqual(['C.A', 'C.Existing'])
  })

  it('replaces existing entries with the same id (upsert)', () => {
    const spec: SpecBlock = {
      ...emptySpec(),
      resources: [{ id: 'R.A', type: 'Resource', level: 'Product', description: 'old', scale: 'old-scale', meter: '', status: '', tolerable: '', goal: '' }],
    }
    const next = applyApprovedToSpec(spec, approvals)
    expect(next.resources).toHaveLength(1)
    expect(next.resources?.[0].scale).toBe('s')  // from approval, not 'old-scale'
  })

  it('applies field edits to existing entries in place', () => {
    const spec: SpecBlock = {
      ...emptySpec(),
      resources: [{ id: 'R.A', type: 'Resource', level: 'Product', description: 'd', scale: 'OLD_SCALE', meter: '', status: '', tolerable: '', goal: '' }],
    }
    const a: ApprovalSet = {
      rEntries: [], sEntries: [], cEntries: [],
      fieldEdits: [{ entryId: 'R.A', field: 'scale', proposedValue: 'NEW_SCALE_QUALIFIED' }],
    }
    const next = applyApprovedToSpec(spec, a)
    expect(next.resources?.[0].scale).toBe('NEW_SCALE_QUALIFIED')
  })

  it('does NOT add resources when none approved (preserves untouched spec.resources)', () => {
    const spec: SpecBlock = {
      ...emptySpec(),
      resources: [{ id: 'R.Existing', type: 'Resource', level: 'Product', description: 'x', scale: '', meter: '', status: '', tolerable: '', goal: '' }],
    }
    const a: ApprovalSet = { rEntries: [], sEntries: [], cEntries: [], fieldEdits: [] }
    const next = applyApprovedToSpec(spec, a)
    expect(next.resources).toHaveLength(1)
    expect(next.resources?.[0].id).toBe('R.Existing')
  })
})
