<script setup lang="ts">
/**
 * PlanguageUniverse — Tom Gilb 2026-06-14 verbatim (initial):
 *   "in or next to the ontology can you bring up a classical ontology universe
 *    that is interesting and easy to navigate, hovering, and a click looks up
 *    the concept?"
 *
 * r41 v7 (Tom Gilb 2026-06-14 "well as we are experiments. all 3") — ships
 * three enhancements together:
 *
 *   A. Fullscreen / lightbox mode — 🌌 Enlarge pin opens a viewport-sized
 *      copy with bigger stars + readable constellation labels.  ESC, click
 *      outside, or ✕ close.  Clicking a star in fullscreen also auto-closes
 *      so the parent picker lands on the new concept.
 *
 *   B. Category labels at constellation centres — small white text at the
 *      centroid of each category's star cluster.  Labels render at 45 %
 *      opacity normally → 100 % when any star in that constellation is
 *      hovered OR the filter has any matches in that category.  Categories
 *      with < 3 concepts get hover-only labels so the universe doesn't
 *      clutter.
 *
 *   C. Embedded filter input — ⌕ field in the header.  Type to dim non-
 *      matching stars to 12 % opacity; matches stay full brightness +
 *      grow 1.5×.  Match count next to the field.  Enter on a single
 *      remaining match navigates to it.  Separate scope from the picker's
 *      main search box — filter operates within the universe only.
 *
 * Loads /planguage-ontology-tree.json (already in /public/, generated by
 * 10.Standard/2.Glossary/PlanguageGlossary/_build-ontology-tree.py).
 */

import { ref, computed, onMounted, onBeforeUnmount, nextTick } from 'vue'
import CloseDot from './CloseDot.vue'  // r41 v18 (Tom Gilb 2026-06-14: "the close button is NOT our sem standard")

interface OntologyConcept {
  id:             string
  kind:           'concept'
  name:           string
  conceptNumber?: string
  type?:          string
  keyedIcon?:     string
  twinUrl?:       string
  definition?:    string
}
interface OntologyCategory {
  id:       string
  kind:     'class'
  name:     string
  slug?:    string
  children: Array<OntologyConcept | OntologyCategory>
}
interface OntologyTree {
  totalConcepts:   number
  totalCategories: number
  tree:            OntologyCategory
}

interface StarLayout {
  concept:  OntologyConcept
  category: string
  cx:       number
  cy:       number
  r:        number
  color:    string
}

interface ConstellationLabel {
  name:     string
  color:    string
  cx:       number  // centroid x
  cy:       number  // centroid y
  size:     number  // concept count
}

const emit = defineEmits<{
  (e: 'select-concept', name: string): void
}>()

withDefaults(defineProps<{
  size?: number
}>(), {
  size: 720,
})

const _tree = ref<OntologyTree | null>(null)
const _error = ref<string | null>(null)
const _hoveredStar = ref<StarLayout | null>(null)
const _hoveredCategory = ref<string | null>(null)
const _hoverX = ref(0)
const _hoverY = ref(0)

// A — fullscreen lightbox state
const _fullscreen = ref(false)
function openFullscreen(): void {
  _fullscreen.value = true
  // Lock background scroll
  if (typeof document !== 'undefined') {
    document.body.style.overflow = 'hidden'
  }
}
function closeFullscreen(): void {
  _fullscreen.value = false
  if (typeof document !== 'undefined') {
    document.body.style.overflow = ''
  }
}
function _onKey(e: KeyboardEvent): void {
  if (e.key === 'Escape' && _fullscreen.value) {
    e.stopPropagation()
    closeFullscreen()
  }
  // r41 v25 (Tom Gilb 2026-06-14 verbatim: "black window stuck in place") —
  // Escape also clears any stranded HoverHint.  Composes with the scroll +
  // mouseleave clearers below.
  if (e.key === 'Escape' && _hoveredStar.value) {
    _hoveredStar.value = null
    _hoveredCategory.value = null
  }
}

// r41 v25 — Stranded-HoverHint fix.
//
// Bug: the floating HoverHint uses `position: fixed`, so when the picker body
// scrolls past the Universe SVG OR the cursor exits the SVG between stars
// (without crossing any star's edge), no `mouseleave` fires on the <g> and
// `_hoveredStar` stays set.  The black box hangs in place over whatever
// content scrolled into its viewport coords — e.g. the Task ontology diagram.
//
// Three defensive clearers:
//   (1) @mouseleave on the SVG + the wrap div (template) — any cursor exit
//   (2) capture-phase window 'scroll' + 'wheel' listeners (here) — any scroll
//       inside any ancestor clears the HoverHint
//   (3) Escape key (above) — explicit dismissal affordance
function _clearStrandedHint(): void {
  if (_hoveredStar.value) {
    _hoveredStar.value = null
    _hoveredCategory.value = null
  }
}

onMounted(() => {
  document.addEventListener('keydown', _onKey, true)
  // Capture phase + passive so we hear scroll on every ancestor (the picker
  // body, the modal, the window) without interfering with normal scrolling.
  window.addEventListener('scroll', _clearStrandedHint, { capture: true, passive: true })
  window.addEventListener('wheel',  _clearStrandedHint, { capture: true, passive: true })
})
onBeforeUnmount(() => {
  document.removeEventListener('keydown', _onKey, true)
  window.removeEventListener('scroll', _clearStrandedHint, { capture: true } as EventListenerOptions)
  window.removeEventListener('wheel',  _clearStrandedHint, { capture: true } as EventListenerOptions)
  // Defensive — release background scroll lock if we get unmounted mid-fullscreen
  if (typeof document !== 'undefined') document.body.style.overflow = ''
})

// C — embedded filter
const _filterText = ref('')
const _filterInputRef = ref<HTMLInputElement | null>(null)
const _filterInputFsRef = ref<HTMLInputElement | null>(null)

const PALETTE = [
  '#a78bfa', '#6ee7b7', '#fbbf24', '#fb923c', '#f87171',
  '#60a5fa', '#22d3ee', '#c084fc', '#fde68a', '#67e8f9',
]

onMounted(async () => {
  try {
    const res = await fetch(`/planguage-ontology-tree.json?v=${Date.now() % 100000}`)
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    _tree.value = await res.json()
  } catch (e) {
    _error.value = `Could not load /planguage-ontology-tree.json: ${(e as Error).message}`
    console.warn('[PlanguageUniverse]', _error.value)
  }
})

const categories = computed<Array<{ name: string; concepts: OntologyConcept[] }>>(() => {
  const t = _tree.value
  if (!t) return []
  const out: Array<{ name: string; concepts: OntologyConcept[] }> = []
  for (const cat of t.tree.children) {
    if (cat.kind !== 'class') continue
    const concepts = cat.children.filter((x): x is OntologyConcept => x.kind === 'concept')
    if (concepts.length === 0) continue
    out.push({ name: cat.name, concepts })
  }
  out.sort((a, b) => b.concepts.length - a.concepts.length)
  return out
})

const stars = computed<StarLayout[]>(() => {
  const cats = categories.value
  if (cats.length === 0) return []
  const out: StarLayout[] = []
  const centreX = 360
  const centreY = 360
  const innerR = 90
  const outerR = 330
  const totalWeight = cats.reduce((s, c) => s + Math.sqrt(c.concepts.length), 0)
  let angleSoFar = -Math.PI / 2
  cats.forEach((cat, i) => {
    const slice = (Math.sqrt(cat.concepts.length) / totalWeight) * Math.PI * 2
    const colour = PALETTE[i % PALETTE.length]
    cat.concepts.forEach((concept, j) => {
      const tRadial = cat.concepts.length === 1 ? 0.5 : j / (cat.concepts.length - 1)
      const r = innerR + tRadial * (outerR - innerR)
      const tAngular = cat.concepts.length === 1 ? 0.5 : (j % 7) / 7
      const angle = angleSoFar + slice * (0.15 + tAngular * 0.7)
      const n = parseInt(concept.conceptNumber ?? '500', 10) || 500
      const baseR = 2.2 + Math.max(0, (500 - n) / 350) * 3
      out.push({
        concept,
        category: cat.name,
        cx: centreX + Math.cos(angle) * r,
        cy: centreY + Math.sin(angle) * r,
        r: baseR,
        color: colour,
      })
    })
    angleSoFar += slice
  })
  return out
})

// B — constellation centroid labels
const constellationLabels = computed<ConstellationLabel[]>(() => {
  const map = new Map<string, { cxSum: number; cySum: number; count: number; color: string }>()
  for (const s of stars.value) {
    const e = map.get(s.category) ?? { cxSum: 0, cySum: 0, count: 0, color: s.color }
    e.cxSum += s.cx
    e.cySum += s.cy
    e.count++
    e.color = s.color
    map.set(s.category, e)
  }
  return Array.from(map.entries()).map(([name, e]) => ({
    name,
    color:  e.color,
    cx:     e.cxSum / e.count,
    cy:     e.cySum / e.count,
    size:   e.count,
  }))
})

// C — filter-matched concept ids
const filteredStarIds = computed<Set<string>>(() => {
  const q = _filterText.value.trim().toLowerCase()
  if (!q) return new Set()  // empty = no filter applied (all stars rendered at full brightness)
  const out = new Set<string>()
  for (const s of stars.value) {
    if (
      s.concept.name.toLowerCase().includes(q)
      || s.category.toLowerCase().includes(q)
      || (s.concept.conceptNumber ?? '').includes(q)
      || (s.concept.definition ?? '').toLowerCase().includes(q)
    ) {
      out.add(s.concept.id)
    }
  }
  return out
})

const filterActive = computed(() => _filterText.value.trim().length > 0)
const filterMatchCount = computed(() => filteredStarIds.value.size)

const filteredCategories = computed<Set<string>>(() => {
  if (!filterActive.value) return new Set()
  const out = new Set<string>()
  for (const s of stars.value) {
    if (filteredStarIds.value.has(s.concept.id)) out.add(s.category)
  }
  return out
})

function isStarVisible(s: StarLayout): { opacity: number; rMul: number } {
  if (!filterActive.value) return { opacity: 1, rMul: 1 }
  if (filteredStarIds.value.has(s.concept.id)) return { opacity: 1, rMul: 1.5 }
  return { opacity: 0.12, rMul: 1 }
}

function isCategoryLit(name: string): boolean {
  // B — label brightening logic:
  //   - filter active AND this category has matches → bright
  //   - any star in this category hovered → bright
  //   - otherwise dim (or hidden for small constellations)
  if (filterActive.value && filteredCategories.value.has(name)) return true
  if (_hoveredCategory.value === name) return true
  return false
}

function categoryLabelOpacity(c: ConstellationLabel): number {
  if (isCategoryLit(c.name)) return 1
  // Small constellations only show on hover/filter
  if (c.size < 3) return 0
  return 0.42
}

function onStarHover(s: StarLayout, ev: MouseEvent): void {
  _hoveredStar.value = s
  _hoveredCategory.value = s.category
  _hoverX.value = ev.clientX
  _hoverY.value = ev.clientY
}
function onStarMouseMove(ev: MouseEvent): void {
  _hoverX.value = ev.clientX
  _hoverY.value = ev.clientY
}
function onStarLeave(): void {
  _hoveredStar.value = null
  _hoveredCategory.value = null
}
function onStarClick(s: StarLayout): void {
  emit('select-concept', s.concept.name)
  if (_fullscreen.value) closeFullscreen()
}

function onFilterEnter(): void {
  // If exactly one match, navigate to it
  if (filterMatchCount.value === 1) {
    const id = Array.from(filteredStarIds.value)[0]
    const s = stars.value.find(x => x.concept.id === id)
    if (s) onStarClick(s)
  }
}

function clearFilter(): void {
  _filterText.value = ''
  if (_fullscreen.value) {
    nextTick(() => _filterInputFsRef.value?.focus())
  } else {
    nextTick(() => _filterInputRef.value?.focus())
  }
}

function _shortDef(d: string | undefined): string {
  if (!d) return ''
  const oneLine = d.replace(/\s+/g, ' ').trim()
  return oneLine.length > 240 ? oneLine.slice(0, 237) + '…' : oneLine
}
</script>

<template>
  <div class="gilb-universe-host">
    <div v-if="_error" class="text-xs text-rose-700 bg-rose-50 border border-rose-200 rounded p-3 italic">
      <strong>Universe unavailable:</strong> {{ _error }}
    </div>
    <div v-else-if="!_tree" class="text-xs text-slate-400 italic p-4 text-center">
      Loading the 663-concept Planguage universe…
    </div>
    <div v-else>
      <!-- HEADER with filter (C) + enlarge button (A) -->
      <div class="flex items-center gap-2 mb-2 px-3 py-1.5 rounded bg-indigo-50 border border-indigo-200 flex-wrap">
        <span class="text-base">🌌</span>
        <span class="text-[10px] font-extrabold uppercase tracking-wider text-indigo-800 shrink-0">Planguage Universe</span>
        <span class="text-[10px] text-slate-600 shrink-0">{{ _tree.totalConcepts }} concepts · {{ categories.length }} constellations</span>

        <!-- C — filter input -->
        <!-- r41 v19 (Tom Gilb 2026-06-14 "that mag glass left of filter
             universe is too small to see") + accessibility_tom baseline (Tom
             is 85 — text-sm minimum on content) — bumped icon + input font
             from text-[11px] to text-base + text-sm respectively for legibility. -->
        <div class="flex items-center gap-1.5 ml-auto">
          <span class="text-lg text-indigo-700 font-bold leading-none" aria-hidden="true">⌕</span>
          <input
            ref="_filterInputRef"
            v-model="_filterText"
            type="text"
            placeholder="filter universe — name, category, def…"
            class="text-sm px-3 py-1.5 border border-indigo-300 rounded bg-white focus:outline-none focus:ring-2 focus:ring-indigo-200 focus:border-indigo-500 w-64"
            title="Filter the universe — type any word from a concept name, category, definition, or concept number. Press Enter to navigate when one match remains. Separate scope from the picker's main search box."
            @keydown.enter="onFilterEnter"
          />
          <span v-if="filterActive" class="text-[10px] font-bold" :class="filterMatchCount > 0 ? 'text-emerald-700' : 'text-rose-600'">
            {{ filterMatchCount }} match{{ filterMatchCount === 1 ? '' : 'es' }}
          </span>
          <button
            v-if="filterActive"
            type="button"
            class="text-[10px] px-1.5 py-0.5 rounded bg-slate-200 text-slate-700 hover:bg-slate-300"
            title="Clear filter"
            @click="clearFilter"
          >✕</button>
        </div>

        <!-- A — enlarge button -->
        <button
          type="button"
          class="text-[10px] font-bold px-2 py-1 rounded bg-indigo-600 text-white hover:bg-indigo-700 shrink-0"
          title="🌌 Enlarge the universe to fullscreen — bigger stars, readable constellation labels.  Click any star in fullscreen to navigate AND auto-close back to the picker.  Esc / outside-click / ✕ also close."
          @click="openFullscreen"
        >🌌 Enlarge</button>
      </div>

      <!-- INLINE SVG starfield -->
      <!-- r41 v25 (Tom Gilb 2026-06-14 "black window stuck in place") —
           @mouseleave on the wrap + SVG so any cursor exit clears the
           floating HoverHint, not just per-star edge-crossings. -->
      <div class="gilb-universe-svg-wrap" @mouseleave="onStarLeave">
        <svg
          viewBox="0 0 720 720"
          xmlns="http://www.w3.org/2000/svg"
          @mousemove="onStarMouseMove"
          @mouseleave="onStarLeave"
        >
          <defs>
            <radialGradient id="universeBackdrop" cx="50%" cy="50%" r="55%">
              <stop offset="0%" stop-color="#1e1b4b" />
              <stop offset="60%" stop-color="#0f0f23" />
              <stop offset="100%" stop-color="#020617" />
            </radialGradient>
          </defs>

          <rect width="720" height="720" fill="url(#universeBackdrop)" />

          <circle cx="360" cy="360" r="90"  fill="none" stroke="#ffffff" stroke-opacity="0.04" />
          <circle cx="360" cy="360" r="180" fill="none" stroke="#ffffff" stroke-opacity="0.04" />
          <circle cx="360" cy="360" r="270" fill="none" stroke="#ffffff" stroke-opacity="0.04" />
          <circle cx="360" cy="360" r="330" fill="none" stroke="#ffffff" stroke-opacity="0.04" />

          <!-- Stars -->
          <g
            v-for="s in stars"
            :key="s.concept.id"
            class="gilb-universe-star"
            :class="{ 'gilb-universe-star--hovered': _hoveredStar?.concept.id === s.concept.id }"
            :opacity="isStarVisible(s).opacity"
            @mouseenter="(ev) => onStarHover(s, ev)"
            @mouseleave="onStarLeave"
            @click="onStarClick(s)"
          >
            <circle :cx="s.cx" :cy="s.cy" :r="s.r * 3.5" :fill="s.color" fill-opacity="0" class="gilb-universe-halo" />
            <circle :cx="s.cx" :cy="s.cy" :r="s.r * isStarVisible(s).rMul" :fill="s.color" />
          </g>

          <!-- B — constellation labels at centroids -->
          <g class="gilb-universe-labels">
            <text
              v-for="c in constellationLabels"
              :key="'lbl-' + c.name"
              :x="c.cx"
              :y="c.cy"
              text-anchor="middle"
              dominant-baseline="middle"
              :font-size="isCategoryLit(c.name) ? 11 : 9"
              font-weight="700"
              :fill="isCategoryLit(c.name) ? '#ffffff' : c.color"
              :opacity="categoryLabelOpacity(c)"
              style="pointer-events: none; transition: opacity 0.2s ease, font-size 0.2s ease;"
            >{{ c.name }}</text>
          </g>

          <!-- Gravitational core marker -->
          <circle cx="360" cy="360" r="6" fill="#fde68a" />
          <text x="360" y="360" text-anchor="middle" dominant-baseline="middle" font-size="10" font-weight="800" fill="#fde68a" dy="-12">PLANGUAGE</text>
        </svg>
      </div>

      <!-- Floating hover tooltip — inline mode -->
      <div
        v-if="_hoveredStar && !_fullscreen"
        class="gilb-universe-tooltip"
        :style="{ left: (_hoverX + 14) + 'px', top: (_hoverY + 14) + 'px' }"
      >
        <div class="flex items-center gap-1.5">
          <span class="text-[10px] font-extrabold uppercase tracking-wider" :style="{ color: _hoveredStar.color }">{{ _hoveredStar.category }}</span>
          <span class="text-[10px] text-slate-400">·</span>
          <span class="text-[10px] font-mono text-slate-400">*{{ _hoveredStar.concept.conceptNumber }}</span>
        </div>
        <div class="text-sm font-extrabold text-white mt-0.5">{{ _hoveredStar.concept.name }}</div>
        <div v-if="_shortDef(_hoveredStar.concept.definition)" class="text-[11px] text-slate-200 mt-1 leading-snug">{{ _shortDef(_hoveredStar.concept.definition) }}</div>
        <div class="text-[10px] text-violet-300 mt-1.5 italic">↩ Click the star to navigate</div>
      </div>
    </div>

    <!-- A — FULLSCREEN LIGHTBOX ─────────────────────────────────────────── -->
    <Teleport to="body">
      <div
        v-if="_fullscreen"
        class="fixed inset-0 z-[1850] bg-slate-950/95 backdrop-blur-sm flex items-center justify-center p-4"
        @click.self="closeFullscreen"
        @mousemove="onStarMouseMove"
      >
        <div
          class="w-full h-full max-w-[1600px] max-h-[96vh] flex flex-col overflow-hidden rounded-2xl shadow-2xl bg-slate-900 border border-indigo-700"
          @click.stop
        >
          <!-- Lightbox header -->
          <header class="flex items-center gap-2 px-5 py-3 border-b border-indigo-800 bg-gradient-to-r from-indigo-950 to-slate-900 shrink-0 flex-wrap">
            <!-- r41 v24 (Universal-Back-Navigation rule) — ← Back at far left
                 returns to the inline universe in the parent picker. -->
            <button
              type="button"
              class="px-3 py-1 rounded-md text-lg font-extrabold bg-slate-800 text-indigo-100 hover:bg-indigo-700 hover:text-white border border-indigo-700 leading-none transition-colors"
              title="← Back — close fullscreen and return to the inline Universe view in the picker.  Esc / outside-click / red close also dismiss."
              @click="closeFullscreen"
            >←</button>
            <span class="text-2xl">🌌</span>
            <div>
              <div class="text-base font-extrabold text-white">Planguage Universe — fullscreen</div>
              <div class="text-[10px] text-slate-400">{{ _tree?.totalConcepts ?? 0 }} concepts · {{ categories.length }} constellations · ← Back / Esc / outside-click / red close all return to inline</div>
            </div>

            <!-- C — filter in fullscreen (reuses same _filterText) -->
            <!-- r41 v19 — same accessibility bump as the inline filter. -->
            <div class="flex items-center gap-1.5 ml-auto">
              <span class="text-xl text-indigo-200 font-bold leading-none" aria-hidden="true">⌕</span>
              <input
                ref="_filterInputFsRef"
                v-model="_filterText"
                type="text"
                placeholder="filter — name, category, def, *N…"
                class="text-sm px-3 py-1.5 border border-indigo-600 rounded bg-slate-800 text-white focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:border-indigo-400 w-72 placeholder:text-slate-500"
                title="Filter the universe — type any word from a concept name, category, definition, or concept number. Press Enter to navigate when one match remains."
                @keydown.enter="onFilterEnter"
              />
              <span v-if="filterActive" class="text-xs font-bold" :class="filterMatchCount > 0 ? 'text-emerald-400' : 'text-rose-400'">
                {{ filterMatchCount }} match{{ filterMatchCount === 1 ? '' : 'es' }}
              </span>
              <button
                v-if="filterActive"
                type="button"
                class="text-xs px-2 py-1 rounded bg-slate-700 text-slate-200 hover:bg-slate-600"
                title="Clear filter"
                @click="clearFilter"
              >✕</button>
            </div>

            <!-- r41 v18 (Tom Gilb 2026-06-14 "the close button is NOT our sem
                 standard") — canonical CloseDot at END of header.  Esc +
                 backdrop click still bound; CloseDot is the third affordance. -->
            <CloseDot
              size="lg"
              aria-label="Close the Planguage Universe fullscreen view"
              class="ml-2"
              @click="closeFullscreen"
            />
          </header>

          <!-- Fullscreen SVG -->
          <!-- r41 v25 — @mouseleave on the wrap + SVG to clear stranded
               HoverHint when cursor exits between stars. -->
          <div class="flex-1 min-h-0 overflow-hidden bg-slate-950 flex items-center justify-center" @mouseleave="onStarLeave">
            <svg
              viewBox="0 0 720 720"
              xmlns="http://www.w3.org/2000/svg"
              style="width: 100%; height: 100%; max-height: 90vh;"
              preserveAspectRatio="xMidYMid meet"
              @mouseleave="onStarLeave"
            >
              <defs>
                <radialGradient id="universeBackdropFs" cx="50%" cy="50%" r="55%">
                  <stop offset="0%" stop-color="#1e1b4b" />
                  <stop offset="60%" stop-color="#0f0f23" />
                  <stop offset="100%" stop-color="#020617" />
                </radialGradient>
              </defs>
              <rect width="720" height="720" fill="url(#universeBackdropFs)" />
              <circle cx="360" cy="360" r="90"  fill="none" stroke="#ffffff" stroke-opacity="0.05" />
              <circle cx="360" cy="360" r="180" fill="none" stroke="#ffffff" stroke-opacity="0.05" />
              <circle cx="360" cy="360" r="270" fill="none" stroke="#ffffff" stroke-opacity="0.05" />
              <circle cx="360" cy="360" r="330" fill="none" stroke="#ffffff" stroke-opacity="0.05" />

              <g
                v-for="s in stars"
                :key="'fs-' + s.concept.id"
                class="gilb-universe-star"
                :class="{ 'gilb-universe-star--hovered': _hoveredStar?.concept.id === s.concept.id }"
                :opacity="isStarVisible(s).opacity"
                @mouseenter="(ev) => onStarHover(s, ev)"
                @mouseleave="onStarLeave"
                @click="onStarClick(s)"
              >
                <circle :cx="s.cx" :cy="s.cy" :r="s.r * 3.5" :fill="s.color" fill-opacity="0" class="gilb-universe-halo" />
                <circle :cx="s.cx" :cy="s.cy" :r="s.r * isStarVisible(s).rMul" :fill="s.color" />
              </g>

              <g>
                <text
                  v-for="c in constellationLabels"
                  :key="'fs-lbl-' + c.name"
                  :x="c.cx"
                  :y="c.cy"
                  text-anchor="middle"
                  dominant-baseline="middle"
                  :font-size="isCategoryLit(c.name) ? 13 : 11"
                  font-weight="700"
                  :fill="isCategoryLit(c.name) ? '#ffffff' : c.color"
                  :opacity="categoryLabelOpacity(c)"
                  style="pointer-events: none; transition: opacity 0.2s ease, font-size 0.2s ease;"
                >{{ c.name }}</text>
              </g>

              <circle cx="360" cy="360" r="6" fill="#fde68a" />
              <text x="360" y="360" text-anchor="middle" dominant-baseline="middle" font-size="11" font-weight="800" fill="#fde68a" dy="-13">PLANGUAGE</text>
            </svg>
          </div>

          <!-- Footer hint -->
          <footer class="px-5 py-2 border-t border-indigo-800 bg-slate-900 text-[11px] text-slate-400 shrink-0 flex items-center gap-3 flex-wrap">
            <span>🖱 hover any star · click to navigate (auto-closes lightbox)</span>
            <span class="text-slate-600">·</span>
            <span>⌨ Enter on a single filter match → navigate</span>
            <span class="text-slate-600">·</span>
            <span>Esc / click outside / ✕ → close</span>
          </footer>
        </div>

        <!-- Floating tooltip in fullscreen — bigger, lighter -->
        <div
          v-if="_hoveredStar"
          class="gilb-universe-tooltip gilb-universe-tooltip--fs"
          :style="{ left: (_hoverX + 16) + 'px', top: (_hoverY + 16) + 'px' }"
        >
          <div class="flex items-center gap-1.5">
            <span class="text-[11px] font-extrabold uppercase tracking-wider" :style="{ color: _hoveredStar.color }">{{ _hoveredStar.category }}</span>
            <span class="text-[11px] text-slate-400">·</span>
            <span class="text-[11px] font-mono text-slate-400">*{{ _hoveredStar.concept.conceptNumber }}</span>
          </div>
          <div class="text-base font-extrabold text-white mt-0.5">{{ _hoveredStar.concept.name }}</div>
          <div v-if="_shortDef(_hoveredStar.concept.definition)" class="text-[12px] text-slate-200 mt-1 leading-snug">{{ _shortDef(_hoveredStar.concept.definition) }}</div>
          <div class="text-[10px] text-violet-300 mt-1.5 italic">↩ Click the star to navigate · lightbox closes automatically</div>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<style scoped>
.gilb-universe-host { width: 100%; }
.gilb-universe-svg-wrap {
  border-radius: 12px;
  overflow: hidden;
  box-shadow: 0 4px 16px rgba(15, 23, 42, 0.4);
  background: #020617;
}
.gilb-universe-svg-wrap svg { display: block; width: 100%; height: auto; }

.gilb-universe-star { cursor: pointer; transition: filter 0.18s ease, opacity 0.18s ease; }
.gilb-universe-star circle:nth-child(2) {
  transition: r 0.18s ease;
  filter: drop-shadow(0 0 1.5px rgba(255, 255, 255, 0.5));
}
.gilb-universe-star:hover circle:nth-child(2),
.gilb-universe-star--hovered circle:nth-child(2) {
  filter: drop-shadow(0 0 8px rgba(255, 255, 255, 0.9));
}
.gilb-universe-halo { transition: fill-opacity 0.18s ease; pointer-events: none; }
.gilb-universe-star:hover .gilb-universe-halo,
.gilb-universe-star--hovered .gilb-universe-halo { fill-opacity: 0.25 !important; }

/* Tooltip */
.gilb-universe-tooltip {
  position: fixed;
  z-index: 1900;
  pointer-events: none;
  max-width: 320px;
  padding: 8px 12px;
  background: rgba(15, 23, 42, 0.96);
  color: #ffffff;
  border-radius: 6px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.45);
  border: 1px solid rgba(167, 139, 250, 0.4);
}
.gilb-universe-tooltip--fs {
  max-width: 420px;
  padding: 10px 14px;
  z-index: 1950;
}
</style>
