// UNIT_TYPE=Utility
// endsAndMeans — Iter 2.5 parser lexicon for the Ends-vs-Means split.
//
// Canonical source (DO NOT EDIT this file without re-reading these slides):
//   Tom Gilb, "Ends and Means" — Berlin 21 May 2026 MASTER deck (46 pages).
//   Local: 5 - Project/SEM App/assets/Ends and Means Berlin 21May2026 MASTER.pdf
//
// Specific slides this file implements:
//   • Slide 4 — End definition: "Future requirement, Objective, Goal, Aim,
//     Target, Value." (concept *100)
//   • Slide 6 — Means definition + synonyms: "Design Idea, Solution, Strategy,
//     Process Improvement Suggestion, Architecture, Ways, The How."
//   • Slide 8 — Keeney 3-level hierarchy: Fundamental Objectives → Strategic
//     Objectives → Means Objectives. One level's End = next level's Means.
//   • Slide 11 — Schopenhauer: "the confusion of ends and means"
//   • Slide 13 — Einstein: "the perfection of means and the confusion of ends
//     characterize our age."
//   • Slide 16 — Juran 1992 stated-needs vs real-needs: Food → Nourishment;
//     Auto → Transportation; House paint → Colorful-appearance + Freedom-
//     from-maintenance. This is the EXACT class of bug the old parser had
//     (stated need = means, real need = end). Iter 2.5 fixes it.
//   • Slide 20 — Ends spec table format: Value Tag / Value Full Name /
//     Ambition Level / Scale of Measure / Meter / Today's Status / Tolerable
//     Level / Wish Level. (Used by Iter 3, not yet here.)
//
// Tom's corrective examples (2026-05-14 chat):
//   "Windows S, need Cleanliness V, = improvement by washing m=means.
//    Garden=S, needs nourishment: Ends, by watering = means."
// → washing/watering are Means; Cleanliness/Nourishment are the Ends.
// → "by" is the Keeney-hierarchy connective between End and Means.
//
// The old parser tagged "washing", "watering", "renewal", "deletion",
// "new tyres", "upgrade" as Values. That is the category error this file
// repairs.

/**
 * Tier A — action nominals (gerunds and -ion / -ment / -ance nouns).
 * Each entry is a single lower-case lemma. Plural and -ing forms are
 * generated programmatically by `isMeansToken`.
 *
 * Source: Berlin slide 6 Means synonyms list, expanded with the everyday
 * action-nominals Tom used in his cabin/garden/car/contract examples.
 */
export const MEANS_TIER_A: ReadonlySet<string> = new Set([
  // Tom's anchor examples (2026-05-14)
  'washing', 'watering', 'renewal', 'deletion',
  // Cleaning + grounds
  'cleaning', 'sweeping', 'mowing', 'pruning', 'fertilizing', 'fertilising',
  'polishing', 'oiling', 'lubrication', 'dusting', 'vacuuming',
  // Building + envelope
  'painting', 'sealing', 'insulation', 'installation', 'weatherproofing',
  'caulking', 'roofing', 'rendering', 'plastering',
  // Lifecycle on objects
  'replacement', 'maintenance', 'repair', 'repairs', 'servicing', 'service',
  'inspection', 'refurbishment', 'renovation', 'restoration', 'overhaul',
  'rebuild', 'rebuilding',
  // Capability / functionality
  'upgrade', 'upgrading', 'downgrade', 'reconfiguration', 'calibration',
  'tuning', 'optimisation', 'optimization',
  // IT / digital
  'defragmenting', 'patching', 'updating', 'backup', 'backups', 'migration',
  'sync', 'syncing',
  // Compliance + governance
  'audit', 'auditing', 'review', 'verification', 'certification',
  'documentation', 'reporting', 'signoff', 'sign-off', 'approval',
  // Skills + culture
  'training', 'coaching', 'mentoring', 'onboarding', 'reskilling', 'upskilling',
  // Process improvement (Berlin slide 6 includes "Process Improvement Suggestion")
  'automation', 'streamlining', 'standardisation', 'standardization',
  'consolidation', 'rationalisation', 'rationalization',
])

/**
 * Tier C — Keeney-hierarchy connectives (Berlin slide 8). When these
 * appear between Y and Z in "X needs Y [connective] Z", Y is the End and
 * Z is the Means — regardless of whether Y/Z are individually classified
 * as quality or action nouns. The preposition itself disambiguates.
 *
 * "garden needs nourishment by watering"
 *   S = garden, V = nourishment, M = watering — no inference needed.
 */
export const KEENEY_CONNECTIVES = ['by', 'through', 'via', 'using', 'with'] as const

/**
 * Regex to match the connective between Y and Z, capturing both clauses.
 * Note `with` is in KEENEY_CONNECTIVES for awareness but DELIBERATELY
 * omitted from this regex because `splitValueWithRole` in SEMEntryForm
 * already claims "with" for stakeholder roles ("collaborate with the team").
 * Adding it here would clash with that rule.
 */
export const KEENEY_RE = /^(.+?)\s+(?:by|through|via|using)\s+(.+)$/i

/**
 * Quality nouns — when Y is one of these in "X needs Y", Y is definitively
 * an End (Value), regardless of any other rule. Short-circuits Tier A
 * checks so we never mis-tag "cleanliness" or "nourishment" as Means.
 */
export const QUALITY_NOUNS: ReadonlySet<string> = new Set([
  'cleanliness', 'nourishment', 'hydration', 'safety', 'security', 'privacy',
  'compliance', 'reliability', 'availability', 'functionality', 'usability',
  'performance', 'weatherproofing', 'comfort', 'appearance', 'tidiness',
  'freshness', 'health', 'validity', 'accuracy', 'integrity', 'durability',
  'longevity', 'sustainability', 'efficiency', 'capability', 'skill',
  'productivity', 'quality', 'speed', 'accuracy', 'transparency',
  'fairness', 'inclusion', 'accessibility', 'responsiveness',
  'profitability', 'growth', 'retention', 'satisfaction', 'wellbeing',
])

/**
 * Means → suggested End map. Seeded by Juran 1992 (Berlin slide 16) and
 * Tom's cabin/garden/car corrective examples (2026-05-14).
 *
 * **Honesty rule.** Any End inferred from this map is marked with the
 * `(?)` suffix in the parsed output so the user SEES it was inferred,
 * not silently invented. Berlin slide 11 (Schopenhauer) warns the
 * confusion of ends and means is the central danger.
 *
 * Keys are the lower-case lemma. Use `inferEndForMeans()` rather than
 * reading this directly so plurals and -ing variants resolve correctly.
 */
export const MEANS_TO_END: ReadonlyMap<string, string> = new Map<string, string>([
  ['washing',         'Cleanliness'],
  ['cleaning',        'Cleanliness'],
  ['watering',        'Nourishment'],
  ['fertilizing',     'Nourishment'],
  ['fertilising',     'Nourishment'],
  ['sweeping',        'Tidiness'],
  ['mowing',          'Tidiness'],
  ['dusting',         'Tidiness'],
  ['vacuuming',       'Tidiness'],
  ['pruning',         'Health'],
  ['polishing',       'Appearance'],
  ['painting',        'Appearance'],
  ['oiling',          'Reliability'],
  ['lubrication',     'Reliability'],
  ['sealing',         'Weatherproofing'],
  ['caulking',        'Weatherproofing'],
  ['weatherproofing', 'Weatherproofing'],
  ['insulation',      'Energy-efficiency'],
  ['roofing',         'Weatherproofing'],
  ['rendering',       'Weatherproofing'],
  ['plastering',      'Appearance'],
  ['renewal',         'Continued-validity'],
  ['deletion',        'Privacy'],
  ['replacement',     'Functionality'],
  ['maintenance',     'Reliability'],
  ['repair',          'Functionality'],
  ['repairs',         'Functionality'],
  ['servicing',       'Reliability'],
  ['service',         'Reliability'],
  ['inspection',      'Quality'],
  ['refurbishment',   'Appearance'],
  ['renovation',      'Functionality'],
  ['restoration',     'Functionality'],
  ['overhaul',        'Functionality'],
  ['rebuild',         'Functionality'],
  ['rebuilding',      'Functionality'],
  ['upgrade',         'Capability'],
  ['upgrading',       'Capability'],
  ['downgrade',       'Simplicity'],
  ['reconfiguration', 'Functionality'],
  ['calibration',     'Accuracy'],
  ['tuning',          'Performance'],
  ['optimisation',    'Efficiency'],
  ['optimization',    'Efficiency'],
  ['defragmenting',   'Performance'],
  ['patching',        'Security'],
  ['updating',        'Compliance'],
  ['backup',          'Continuity'],
  ['backups',         'Continuity'],
  ['migration',       'Capability'],
  ['sync',            'Consistency'],
  ['syncing',         'Consistency'],
  ['audit',           'Compliance'],
  ['auditing',        'Compliance'],
  ['review',          'Quality'],
  ['verification',    'Accuracy'],
  ['certification',   'Compliance'],
  ['documentation',   'Clarity'],
  ['reporting',       'Transparency'],
  ['signoff',         'Continued-validity'],
  ['sign-off',        'Continued-validity'],
  ['approval',        'Continued-validity'],
  ['training',        'Skill'],
  ['coaching',        'Skill'],
  ['mentoring',       'Skill'],
  ['onboarding',      'Productivity'],
  ['reskilling',      'Capability'],
  ['upskilling',      'Capability'],
  ['automation',      'Efficiency'],
  ['streamlining',    'Efficiency'],
  ['standardisation', 'Consistency'],
  ['standardization', 'Consistency'],
  ['consolidation',   'Efficiency'],
  ['rationalisation', 'Efficiency'],
  ['rationalization', 'Efficiency'],
])

/**
 * Solution-noun patterns (Tier B). Match phrases like "new tyres", "fresh
 * paint", "more storage", "additional units", "replacement parts". These
 * are Means by structure — the noun is the *thing acquired*, not a
 * quality desired of it. The End for "new tyres" is NOT inferable from
 * the structure alone (could be safety / image / grip), so callers leave
 * the End as `null` when only Tier B matches.
 *
 * Deliberately EXCLUDED (2026-05-14 Iter 2.5 refinement): "better X",
 * "improved X", "upgraded X". Those describe a desired quality OF X
 * ("the team wants better yield tracking" = End, not Means) — Berlin
 * slide 4: End is the future requirement / target / value. Letting those
 * adjectives count as Means would mis-classify the most common Value
 * phrasings.
 */
export const SOLUTION_NOUN_PREFIX_RE =
  /^(new|fresh|more|additional|replacement|spare|extra)\s+\w+/i

/** Suffix marker appended to inferred End strings so the chip renderer
 * can detect them and apply amber styling. The user can clear the marker
 * by editing the chip. */
export const INFERRED_SUFFIX = ' (?)'

/** True if the token (lower-cased) is a Means by Tier A or generated form. */
export function isMeansToken(tokenLc: string): boolean {
  if (MEANS_TIER_A.has(tokenLc)) return true
  // Generated -s plural and -ing variants
  if (tokenLc.endsWith('s')  && MEANS_TIER_A.has(tokenLc.slice(0, -1))) return true
  if (tokenLc.endsWith('es') && MEANS_TIER_A.has(tokenLc.slice(0, -2))) return true
  return false
}

/** True if the token (lower-cased) is a Quality noun (End by lexicon). */
export function isQualityToken(tokenLc: string): boolean {
  return QUALITY_NOUNS.has(tokenLc)
}

/**
 * Look up the suggested End for a Means token. Returns the canonical
 * End noun (e.g. "Cleanliness") or `null` if the Means is in the lexicon
 * but has no specific End mapping (callers should leave V as "?").
 */
export function inferEndForMeans(tokenLc: string): string | null {
  const direct = MEANS_TO_END.get(tokenLc)
  if (direct) return direct
  if (tokenLc.endsWith('s')  && MEANS_TO_END.has(tokenLc.slice(0, -1))) {
    return MEANS_TO_END.get(tokenLc.slice(0, -1)) ?? null
  }
  if (tokenLc.endsWith('es') && MEANS_TO_END.has(tokenLc.slice(0, -2))) {
    return MEANS_TO_END.get(tokenLc.slice(0, -2)) ?? null
  }
  return null
}

/** Result shape for `analyzeYClause`. */
export interface YClauseAnalysis {
  /** 'value' = treat Y as an End (existing parser path).
   *  'means' = treat Y as a Means, optionally with inferredEnd. */
  kind: 'value' | 'means'
  /** When kind === 'means', the original Y text (for the means chip). */
  means?: string
  /** When kind === 'means', the suggested End from MEANS_TO_END.
   *  `null` means "Means recognised but no End inferable" → V stays "?". */
  inferredEnd?: string | null
  /** When the input contained a Keeney connective ("by"/"through"/"via"),
   *  Y is split into explicit value + means. No inference needed. */
  explicitValue?: string
  /** When the input contained a Keeney connective, the means side. */
  explicitMeans?: string
}

/**
 * Analyze the Y clause of "[X] needs [Y]" — decide if Y is an End or a
 * Means, and if Means, infer the End where possible.
 *
 * Rules in priority order:
 *   1. Keeney connective ("Y by Z" / "Y through Z" / "Y via Z")
 *      → explicitValue=Y, explicitMeans=Z. No inference.
 *   2. First token is a Quality noun (Tier Q)
 *      → kind='value'. Existing parser path.
 *   3. First token is a Means token (Tier A, with plural/-ing folding)
 *      → kind='means', inferredEnd = MEANS_TO_END[token] OR null.
 *   4. Whole phrase matches Solution-noun prefix ("new X", "fresh X", …)
 *      → kind='means', inferredEnd=null. (Tom's "car needs new tyres".)
 *   5. Default
 *      → kind='value'. Existing parser path (recurses normally).
 */
export function analyzeYClause(y: string): YClauseAnalysis {
  const trimmed = y.trim()
  if (!trimmed) return { kind: 'value' }

  // Rule 1 — Keeney connective ("Y by Z")
  const keeney = trimmed.match(KEENEY_RE)
  if (keeney) {
    return {
      kind: 'means',
      explicitValue: keeney[1].trim(),
      explicitMeans: keeney[2].trim(),
    }
  }

  // Tokenise to get the head noun (skip determiners + adjectives no — keep simple:
  // first content word after stripping leading articles).
  const tokens = trimmed.split(/\s+/).filter(Boolean)
  let head = tokens[0]?.toLowerCase() ?? ''
  // Strip a single leading article so "the watering" / "an upgrade" still match.
  if (/^(the|a|an|some|any|its|their|our|my|your)$/i.test(head) && tokens.length > 1) {
    head = tokens[1].toLowerCase()
  }
  // Strip a single leading determiner-like adjective ("regular maintenance", "annual review")
  if (
    /^(regular|annual|monthly|weekly|daily|periodic|routine|scheduled|emergency|deep|light|heavy|full|partial|quick|thorough)$/i.test(head) &&
    tokens.length > 2
  ) {
    head = tokens[2].toLowerCase()
  }

  // Rule 2 — Quality noun → End
  if (isQualityToken(head)) return { kind: 'value' }

  // Rule 3 — Means token
  if (isMeansToken(head)) {
    return {
      kind: 'means',
      means: trimmed,
      inferredEnd: inferEndForMeans(head),
    }
  }

  // Rule 4 — Solution-noun prefix
  if (SOLUTION_NOUN_PREFIX_RE.test(trimmed)) {
    return {
      kind: 'means',
      means: trimmed,
      inferredEnd: null,
    }
  }

  // Rule 5 — default
  return { kind: 'value' }
}

/** True if the value chip text carries the inferred marker. */
export function isInferredEnd(chipText: string): boolean {
  return chipText.endsWith(INFERRED_SUFFIX)
}

/** Strip the inferred marker for display (chip rendering). */
export function stripInferredMarker(chipText: string): string {
  return isInferredEnd(chipText) ? chipText.slice(0, -INFERRED_SUFFIX.length) : chipText
}

/** Attach the inferred marker to an End string. */
export function withInferredMarker(end: string): string {
  return `${end}${INFERRED_SUFFIX}`
}
