/**
 * useEmlExport.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Universal "email ready pasted" composable — Tom Gilb design rule 2026-05-29.
 *
 * Replaces ALL `mailto:` + paste-instruction flows in the SEM App.
 * `openEml()` downloads a .eml file (RFC 2822 multipart/alternative) that
 * Mail.app opens as a compose-draft window with the HTML body pre-filled.
 * No manual paste required.
 *
 * Architecture note:
 *   macOS registers Mail.app as the handler for `message/rfc822` MIME type.
 *   The generated .eml is a valid RFC 2822 draft — intentionally OMITS
 *   From: / Date: / Message-ID: headers so Mail treats it as a NEW outgoing
 *   draft rather than a received message. The user sees a compose window
 *   with the full coloured HTML content already in the body.
 *
 * Twin-portability:
 *   All functions are pure (no Vue reactivity). Can be ported to any framework
 *   that has access to the DOM (document.createElement, URL.createObjectURL).
 *   For server-side or non-browser environments, call `buildEml()` directly and
 *   persist the returned string via the platform's file API.
 *
 * Resilience:
 *   - Boundary string uses crypto-quality entropy so MIME parsers never
 *     mistake content for a boundary.
 *   - URL.revokeObjectURL is deferred 15 s to survive slow Mail.app launch.
 *   - Graceful fallback: if Blob / URL.createObjectURL is unavailable (e.g.
 *     some private browsing modes) we fall back to a data: URI approach.
 */

// ── Plain-text-to-HTML wrapper ─────────────────────────────────────────────────

/**
 * Wrap a plain-text string in a minimal, styled HTML block suitable for
 * email export. Used for surfaces that only have a text builder (e.g.
 * glyph history, priority info). The result is proper HTML — not pure text —
 * satisfying the Colorful Exports Rule.
 *
 * @param text   The pre-built plain-text body.
 * @param title  Heading rendered above the text block.
 */
export function textToEmailHtml(text: string, title: string): string {
  const esc = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

  return [
    '<div style="font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',sans-serif;',
    'font-size:13px;color:#0f172a;max-width:720px;padding:16px;">',
    `<h2 style="margin:0 0 12px 0;color:#1e293b;border-bottom:2px solid #e2e8f0;`,
    `padding-bottom:8px;">${esc(title)}</h2>`,
    '<pre style="white-space:pre-wrap;font-family:-apple-system,BlinkMacSystemFont,',
    '\'Segoe UI\',sans-serif;font-size:13px;line-height:1.6;margin:0;',
    `background:#f8fafc;border-radius:6px;padding:12px;">${esc(text)}</pre>`,
    '<p style="margin:16px 0 0 0;color:#94a3b8;font-size:11px;">',
    `Generated by SEM App · ${new Date().toISOString().slice(0, 10)}</p>`,
    '</div>',
  ].join('')
}

// ── Core .eml builder ──────────────────────────────────────────────────────────

/**
 * Build a RFC 2822 multipart/alternative email string.
 * The returned string is suitable for writing to a .eml file that
 * Mail.app (and most other desktop email clients) will open as a compose draft.
 *
 * @internal — call `openEml()` from application code; use this only when you
 * need the raw string (e.g. for testing or server-side generation).
 */
export function buildEml(
  htmlBody:  string,
  plainBody: string,
  subject:   string,
  to:        string[] = [],
  cc:        string[] = [],
): string {
  // High-entropy boundary: timestamp + 9 random chars — collision probability
  // is negligible even across thousands of concurrent users.
  const rnd      = Math.random().toString(36).slice(2, 11).padEnd(9, '0')
  const boundary = `SEM_EML_${Date.now()}_${rnd}`

  const lines: string[] = [
    'MIME-Version: 1.0',
    `Subject: ${subject}`,
  ]
  if (to.length) lines.push(`To: ${to.join(', ')}`)
  if (cc.length) lines.push(`Cc: ${cc.join(', ')}`)

  lines.push(
    `Content-Type: multipart/alternative; boundary="${boundary}"`,
    '',
    `--${boundary}`,
    'Content-Type: text/plain; charset=utf-8',
    '',
    plainBody,
    '',
    `--${boundary}`,
    'Content-Type: text/html; charset=utf-8',
    '',
    htmlBody,
    '',
    `--${boundary}--`,
  )

  // RFC 2822 requires CRLF line endings inside email headers/boundaries.
  return lines.join('\r\n')
}

// ── Public API ─────────────────────────────────────────────────────────────────

export interface EmlOptions {
  /** Recipient address list (optional — opens blank To: if omitted). */
  to?: string[]
  /** CC address list (optional). */
  cc?: string[]
  /**
   * Override the auto-generated plain-text fallback.
   * If not provided, plain text is derived by stripping HTML tags from htmlBody.
   */
  plainBody?: string
}

/**
 * Download a .eml file and open it in Mail.app as a pre-filled compose draft.
 *
 * On macOS, the browser creates an <a> element with `download="*.eml"`.
 * macOS opens .eml files with Mail.app by default (message/rfc822 handler),
 * which presents a new compose window with the HTML body already rendered —
 * no manual paste required.
 *
 * @param htmlBody  Full HTML string for the email body (inline styles only —
 *                  CSS rules are stripped by most email clients).
 * @param subject   Email subject line (UTF-8, emoji allowed).
 * @param opts      Optional To/Cc addresses and plain-text override.
 */
export function openEml(
  htmlBody: string,
  subject:  string,
  opts?:    EmlOptions,
): void {
  // Derive plain-text fallback by stripping tags if not explicitly provided.
  const plain = opts?.plainBody
    ?? htmlBody.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim()

  const eml = buildEml(htmlBody, plain, subject, opts?.to ?? [], opts?.cc ?? [])

  // Sanitise filename — strip characters that are problematic across filesystems.
  const safeName = subject
    .replace(/[^a-zA-Z0-9 _\-\.·—]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 60) || 'SEM-Export'

  try {
    const blob = new Blob([eml], { type: 'message/rfc822' })
    const url  = URL.createObjectURL(blob)

    // Open in a new tab WITHOUT the `download` attribute.
    // On macOS Safari, navigating to a blob URL of type message/rfc822 hands
    // off to Mail.app via the OS MIME handler — the compose window opens
    // directly without a Downloads step.  `a.download` would force the file
    // into ~/Downloads and require the user to manually double-click it, which
    // is the old behaviour Tom reported as broken (2026-05-29).
    const a    = document.createElement('a')
    a.href     = url
    a.target   = '_blank'
    a.rel      = 'noopener noreferrer'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)

    // Revoke after 60 s — enough time for Mail.app to read the blob URL,
    // even on a slow machine where Mail.app takes a few seconds to launch.
    setTimeout(() => URL.revokeObjectURL(url), 60_000)
  } catch {
    // Fallback for environments where Blob URLs or window.open are unavailable
    // (e.g. some private-browsing modes). Force-download the .eml so the
    // user can open it manually from ~/Downloads.
    const encoded = encodeURIComponent(eml)
    const a       = document.createElement('a')
    a.href        = `data:message/rfc822,${encoded}`
    a.download    = `${safeName}.eml`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
  }
}
