// UNIT_TYPE=Composable
// usePlanHealthExport — Copy / Email helpers for Plan Health Status + Admin
//
// Both panels need the same "share this PHI snapshot with someone" workflow:
//   • 📋 Copy   — rich-clipboard (HTML + plain-text) so it pastes as a real
//                 Keynote/Numbers grid AND falls back to clean monospace text
//   • ✉️ Email  — opens mailto: with the plain-text body pre-filled
//
// One module so the format stays in sync between panels and a future PDF
// export can reuse the same renderer.

import type { IndexBreakdown, PlanHealthCustom } from './usePlanHealth'

export interface PlanHealthExportInput {
  planName: string
  planVersion: string
  breakdown: IndexBreakdown
  custom: PlanHealthCustom
  /** Caller — included as "Generated by …" footer */
  by: string
}

/**
 * Build both the rich (HTML) and plain (TSV/text) representations of a PHI
 * report. Title block + group breakdown + AI Expert verdicts + recent history.
 */
export function buildPlanHealthReport(input: PlanHealthExportInput): { html: string; text: string; subject: string } {
  const { planName, planVersion, breakdown, custom, by } = input
  const ts = new Date().toISOString().slice(0, 19).replace('T', ' ')
  const indexStr = `${breakdown.index >= 0 ? '+' : ''}${breakdown.index}%`
  const subject = `Plan Health ${indexStr} — ${planName}${planVersion ? ' ' + planVersion : ''}`

  // ── HTML (rich-paste target) ────────────────────────────────────────────
  // Inline styles only — keeps it portable to Keynote / Numbers / Mail.
  const bandColor = breakdown.index < 0 ? '#dc2626'
                  : breakdown.index < 50 ? '#f59e0b'
                  : '#10b981'
  const groupRowsHtml = breakdown.groups.map(g => {
    const sign = g.groupIndex >= 0 ? '+' : ''
    const color = g.groupIndex < 0 ? '#dc2626' : g.groupIndex < 50 ? '#f59e0b' : '#10b981'
    return `<tr>
      <td style="padding:4px 8px;border:1px solid #e2e8f0;white-space:normal;">${escapeHtml(g.groupIcon + ' ' + g.groupLabel)}</td>
      <td style="padding:4px 8px;border:1px solid #e2e8f0;text-align:right;color:${color};font-weight:bold;">${sign}${g.groupIndex}%</td>
      <td style="padding:4px 8px;border:1px solid #e2e8f0;text-align:right;">${(g.groupWeight * 100).toFixed(0)}%</td>
      <td style="padding:4px 8px;border:1px solid #e2e8f0;text-align:right;">${g.aspects.filter(a => !a.disabled).length}</td>
    </tr>`
  }).join('\n')

  const expertRowsHtml = custom.experts.filter(e => e.enabled).map(e => {
    if (!e.lastReview) {
      return `<tr>
        <td style="padding:4px 8px;border:1px solid #e2e8f0;white-space:normal;">${escapeHtml(e.name)} — ${escapeHtml(e.domain)}</td>
        <td style="padding:4px 8px;border:1px solid #e2e8f0;text-align:right;color:#94a3b8;">—</td>
        <td style="padding:4px 8px;border:1px solid #e2e8f0;white-space:normal;color:#94a3b8;font-style:italic;">no review yet</td>
      </tr>`
    }
    const sign = e.lastReview.score >= 0 ? '+' : ''
    const color = e.lastReview.score < 0 ? '#dc2626' : e.lastReview.score < 5 ? '#f59e0b' : '#10b981'
    const refs = e.lastReview.references ?? []
    const refsHtml = refs.length
      ? `<br><span style="font-size:11px;color:#475569;">More: ${refs.map(u => `<a href="${escapeAttr(u)}" style="color:#7c3aed;text-decoration:underline;">${escapeHtml(u)}</a>`).join(' &middot; ')}</span>`
      : ''
    return `<tr>
      <td style="padding:4px 8px;border:1px solid #e2e8f0;white-space:normal;">${escapeHtml(e.name)} — ${escapeHtml(e.domain)}</td>
      <td style="padding:4px 8px;border:1px solid #e2e8f0;text-align:right;color:${color};font-weight:bold;">${sign}${e.lastReview.score}/10</td>
      <td style="padding:4px 8px;border:1px solid #e2e8f0;white-space:normal;">${escapeHtml(e.lastReview.why)}${refsHtml}</td>
    </tr>`
  }).join('\n')

  const recentHistoryHtml = custom.snapshots.slice(-10).reverse().map(s => {
    const sign = s.index >= 0 ? '+' : ''
    return `<tr>
      <td style="padding:4px 8px;border:1px solid #e2e8f0;font-family:monospace;">${s.at.slice(0, 10)}</td>
      <td style="padding:4px 8px;border:1px solid #e2e8f0;">${escapeHtml(s.planVersion || '—')}</td>
      <td style="padding:4px 8px;border:1px solid #e2e8f0;text-align:right;font-weight:bold;">${sign}${s.index}%</td>
      <td style="padding:4px 8px;border:1px solid #e2e8f0;color:#64748b;font-size:11px;">${s.trigger}</td>
    </tr>`
  }).join('\n')

  const html = `<div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;font-size:13px;color:#0f172a;max-width:720px;">
  <h2 style="margin:0 0 4px 0;">🩺 Plan Health Report</h2>
  <p style="margin:0 0 12px 0;color:#64748b;">${escapeHtml(planName)}${planVersion ? ' &middot; ' + escapeHtml(planVersion) : ''} &middot; ${ts}</p>
  <div style="display:inline-block;padding:8px 16px;border-radius:8px;background:${bandColor};color:white;font-size:24px;font-weight:bold;margin-bottom:16px;">
    PHI ${indexStr}
  </div>
  <h3 style="margin:16px 0 6px 0;font-size:14px;">Aspect Group Breakdown</h3>
  <table style="border-collapse:collapse;width:100%;">
    <thead><tr style="background:#f8fafc;">
      <th style="padding:6px 8px;border:1px solid #e2e8f0;text-align:left;">Group</th>
      <th style="padding:6px 8px;border:1px solid #e2e8f0;text-align:right;">Sub-index</th>
      <th style="padding:6px 8px;border:1px solid #e2e8f0;text-align:right;">Weight</th>
      <th style="padding:6px 8px;border:1px solid #e2e8f0;text-align:right;">Aspects</th>
    </tr></thead>
    <tbody>${groupRowsHtml}</tbody>
  </table>
  ${expertRowsHtml ? `<h3 style="margin:16px 0 6px 0;font-size:14px;">🧠 AI Expert Verdicts</h3>
  <table style="border-collapse:collapse;width:100%;">
    <thead><tr style="background:#f5f3ff;">
      <th style="padding:6px 8px;border:1px solid #e2e8f0;text-align:left;">Expert — Domain</th>
      <th style="padding:6px 8px;border:1px solid #e2e8f0;text-align:right;">Score</th>
      <th style="padding:6px 8px;border:1px solid #e2e8f0;text-align:left;">Why?</th>
    </tr></thead>
    <tbody>${expertRowsHtml}</tbody>
  </table>` : ''}
  ${recentHistoryHtml ? `<h3 style="margin:16px 0 6px 0;font-size:14px;">📈 Recent History (last 10)</h3>
  <table style="border-collapse:collapse;width:100%;">
    <thead><tr style="background:#f8fafc;">
      <th style="padding:6px 8px;border:1px solid #e2e8f0;text-align:left;">Date</th>
      <th style="padding:6px 8px;border:1px solid #e2e8f0;text-align:left;">Version</th>
      <th style="padding:6px 8px;border:1px solid #e2e8f0;text-align:right;">PHI</th>
      <th style="padding:6px 8px;border:1px solid #e2e8f0;text-align:left;">Trigger</th>
    </tr></thead>
    <tbody>${recentHistoryHtml}</tbody>
  </table>` : ''}
  <p style="margin:16px 0 0 0;color:#94a3b8;font-size:11px;">Generated by ${escapeHtml(by)} from the SEM app · Plan Health Index methodology</p>
</div>`

  // ── Plain-text (mail body / fallback) ───────────────────────────────────
  const lines: string[] = []
  lines.push(`Plan Health Report`)
  lines.push(`${planName}${planVersion ? ' · ' + planVersion : ''} · ${ts}`)
  lines.push(``)
  lines.push(`PHI: ${indexStr}`)
  lines.push(``)
  lines.push(`ASPECT GROUP BREAKDOWN`)
  for (const g of breakdown.groups) {
    const sign = g.groupIndex >= 0 ? '+' : ''
    lines.push(`  ${g.groupIcon} ${g.groupLabel.padEnd(28)} ${sign}${g.groupIndex}%   weight ${(g.groupWeight * 100).toFixed(0)}%`)
  }
  const enabledExperts = custom.experts.filter(e => e.enabled)
  if (enabledExperts.length) {
    lines.push(``)
    lines.push(`AI EXPERT VERDICTS`)
    for (const e of enabledExperts) {
      if (e.lastReview) {
        const sign = e.lastReview.score >= 0 ? '+' : ''
        lines.push(`  • ${e.name} — ${e.domain}  ${sign}${e.lastReview.score}/10`)
        lines.push(`    "${e.lastReview.why}"`)
        const refs = e.lastReview.references ?? []
        if (refs.length) lines.push(`    More: ${refs.join('  ·  ')}`)
      } else {
        lines.push(`  • ${e.name} — ${e.domain}  (no review yet)`)
      }
    }
  }
  if (custom.snapshots.length) {
    lines.push(``)
    lines.push(`RECENT HISTORY (last 10)`)
    for (const s of custom.snapshots.slice(-10).reverse()) {
      const sign = s.index >= 0 ? '+' : ''
      lines.push(`  ${s.at.slice(0, 10)}  ${(s.planVersion || '—').padEnd(10)} ${sign}${s.index}%  ${s.trigger}`)
    }
  }
  lines.push(``)
  lines.push(`— Generated by ${by} from the SEM app`)
  const text = lines.join('\n')

  return { html, text, subject }
}

function escapeHtml(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

/** href-safe quoting — same rules but kept separate so the helper's intent is
 *  obvious at the call site (mail clients are pickier than browsers). */
function escapeAttr(s: string): string {
  return escapeHtml(s)
}

/**
 * Copy the report to the clipboard. Uses ClipboardItem for rich HTML
 * (Keynote / Numbers / Mail render the table as a real grid) and falls
 * back to plain-text if the browser doesn't support it.
 *
 * Returns true on success, false on any failure.
 */
export async function copyPlanHealthReport(input: PlanHealthExportInput): Promise<boolean> {
  const { html, text } = buildPlanHealthReport(input)
  try {
    if (typeof ClipboardItem !== 'undefined') {
      await navigator.clipboard.write([
        new ClipboardItem({
          'text/html':  new Blob([html], { type: 'text/html' }),
          'text/plain': new Blob([text], { type: 'text/plain' }),
        }),
      ])
      return true
    }
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    try { await navigator.clipboard.writeText(text); return true }
    catch { return false }
  }
}

/**
 * Open the user's default mail client with subject + body pre-filled.
 * `to` and `cc` take comma-separated address lists (typically the Plan
 * Owner emails from `planModel.owners`).
 */
export function emailPlanHealthReport(input: PlanHealthExportInput, to: string[] = [], cc: string[] = []): void {
  const { text, subject } = buildPlanHealthReport(input)
  const params = new URLSearchParams()
  params.set('subject', subject)
  params.set('body', text)
  if (cc.length) params.set('cc', cc.join(','))
  const url = `mailto:${encodeURIComponent(to.join(','))}?${params.toString().replace(/\+/g, '%20')}`
  // Anchor.click() is more reliable than window.location.href in Safari for mailto:
  const a = document.createElement('a')
  a.href = url
  a.style.display = 'none'
  document.body.appendChild(a)
  a.click()
  setTimeout(() => { document.body.removeChild(a) }, 0)
}
